### PR TITLE
Nkprince007 patch 1

### PR DESCRIPTION
**Pull request by nkprince007**

### CODE REVIEW

**Comment by nkprince007** [comment]
Comment on d75428e90822ba144b241fcba11decbd943952b9, file README.md, line 6.

Line is longer than allowed. (170 > 79)

*Origin: LineLengthBear, Section: `all`.*

**Comment by nkprince007** [comment]
Comment on d75428e90822ba144b241fcba11decbd943952b9, file README.md, line 6.

Line is longer than allowed. (170 > 79)

*Origin: LineLengthBear, Section: `all`.*

**Comment by nkprince007** [comment]
Comment on d75428e90822ba144b241fcba11decbd943952b9, file README.md, line 6.

Line is longer than allowed. (170 > 79)

*Origin: LineLengthBear, Section: `all`.*

**Comment by nkprince007** [comment]
@coafile

**Comment by coafile** [comment]
Greetings! I'm the coafile bot and I'm here to get your coafile ready. Sit Tight!

**Comment by coafile** [comment]
```# Generated by coala-quickstart on 28 Jun 2017.
[default]
bears = FilenameBear, InvalidLinkBear
files = **.md
[markdown]
bears = MarkdownBear, DuplicateFileBear, coalaBear, LicenseCheckBear, LineLengthBear
files = **.md
```

**Comment by coafile** [comment]
coafile creation process Successful! :tada: :tada: :tada:


 Next Steps: 

 Step 1: Merge the Pull Request having the .coafile.
 Step 2: Turn on GitMate Integration on this repository.
 Step 3: Turn on code analysis for automated code reviews on your PRs

 Happy Linting! :tada:

**Pull request closed without merging**
